# local development  configuration
config:
  MONGODB_URI: "mongodb://test_user2:Pa$$woRD256$@10.192.5.46:27017/?directConnection=true"
  #MONGODB_URI: "mongodb+srv://sreeramp:B0Ne3Zzk8QJhOAiK@cluster0.jb6ih6x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  DB_NAME: hr_ai_chatbot
  #DB_NAME: HR_bot
  HISTORY_COLLECTION_NAME: history
  HISTORY_COLLECTION_Logs: history_logs
  collection_user: User
  SECRET_KEY: mia_chat_botxxxx
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 30
  CIPHER_KEY: PVmmpjmeRmvPHuoKEiHw5FJntTM2sJAe8baw_8L6RHE=
  #DB_PATH: /app/Sqllite/Bot.db
  # DB_PATH: D:/GENAI/HR_chatbot_GCP_1/Sqllite/Bot.db
  #CHROMA_PATH: /app/chroma_db
  CHROMA_PATH: chroma_db
  RAG_MODEL: gemini-2.5-flash
  EMBEDD_MODEL: text-embedding-004
  API_KEY: AIzaSyA7hjnwNtqS0ejsownrDgMQOulbR7gaLNM
  CHROMA_COLLECTION: langchain
  SQLLITE_CONNECTION_STRING: sqlite:////app/Sqllite/Bot.db
  # SQLLITE_CONNECTION_STRING: sqlite:///D:/GENAI/HR_chatbot_GCP_1/Sqllite/Bot.db
  maxPoolSize : 350






    


     



    


